"""add bookings

Revision ID: 2005b5903bac
Revises: 74cb896204c8
Create Date: 2026-03-26 18:06:22.139452

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "2005b5903bac"
down_revision: Union[str, Sequence[str], None] = "74cb896204c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
