"""add users

Revision ID: 8053b188ede9
Revises: 6417ba478811
Create Date: 2026-03-16 20:19:39.423542

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8053b188ede9"
down_revision: Union[str, Sequence[str], None] = "6417ba478811"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
