"""add bookings repeat

Revision ID: a98cd21017f5
Revises: 2005b5903bac
Create Date: 2026-03-26 18:10:36.105653

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a98cd21017f5"
down_revision: Union[str, Sequence[str], None] = "2005b5903bac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
